"""Layout-independent Profile persistence contract."""
from typing import Protocol
from app.profiles import ActiveProfileBinding, AgentProfile, ProfileFields


class ProfileStore(Protocol):
    def create(self, owner_id: str, fields: ProfileFields) -> AgentProfile: ...
    def read(self, owner_id: str, profile_id: str) -> AgentProfile: ...
    def list(self, owner_id: str) -> tuple[AgentProfile, ...]: ...
    def edit(self, owner_id: str, profile_id: str, expected_revision: int,
             fields: ProfileFields) -> AgentProfile: ...
    def read_binding(self, owner_id: str) -> ActiveProfileBinding: ...
    def select(self, owner_id: str, profile_id: str, expected_profile_revision: int,
               expected_binding_revision: int) -> ActiveProfileBinding: ...
